### post for calculate SIM
POST http://localhost:9090/stakeholder-modelling/calculate_sim
content-type: application/json

{
    "stakeholders": [
        {
            "name": "Stakeholder A",
            "connectionStrength": 0.8,
            "influence": 0.6
        },
        {
            "name": "Stakeholder B",
            "connectionStrength": 0.7,
            "influence": 0.5
        },
        {
            "name": "Stakeholder C",
            "connectionStrength": 0.6,
            "influence": 0.4
        }
    ]
}


### Post request for calculating DSI
POST http://localhost:9090/stakeholder-modelling/calculate_dsi
content-type: application/json

{
    "stakeholders": [
        {"name": "Stakeholder A", "connectionStrength": 0.8, "influence": 0.6},
        {"name": "Stakeholder B", "connectionStrength": 0.5, "influence": 0.9},
        {"name": "Stakeholder C", "connectionStrength": 0.7, "influence": 0.4}
    ],
    "deltaBehavior": [0.2, -0.1, 0.3]
}

### Post request for calculating SNS
POST http://localhost:9090/stakeholder-modelling/calculate_sns
content-type: application/json

{
    "stakeholders": [
        {"name": "Stakeholder A", "connectionStrength": 0.8, "influence": 0.6},
        {"name": "Stakeholder B", "connectionStrength": 0.5, "influence": 0.9},
        {"name": "Stakeholder C", "connectionStrength": 0.7, "influence": 0.4}
    ],
    "deltaBehavior": [0.2, -0.1, 0.3]
}

### Post request for calculating SIS
POST http://localhost:9090/stakeholder-modelling/calculate_sis
content-type: application/json

{
    "stakeholders": [
        {"name": "Stakeholder A", "connectionStrength": 0.8, "influence": 0.6},
        {"name": "Stakeholder B", "connectionStrength": 0.5, "influence": 0.9},
        {"name": "Stakeholder C", "connectionStrength": 0.7, "influence": 0.4}
    ]
}
